# Generated by Django 3.1.2 on 2021-04-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminalDetector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
