# Generated by Django 3.1.2 on 2021-04-30 16:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('criminalDetector', '0002_auto_20210430_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='relativeContact',
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='police',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='police',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
