# Generated by Django 3.1.2 on 2021-04-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminalDetector', '0003_auto_20210430_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='image',
            field=models.ImageField(upload_to='Criminal_Images'),
        ),
    ]
