# Generated by Django 3.1.2 on 2021-05-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminalDetector', '0004_auto_20210430_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='searches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Criminal_Images')),
            ],
        ),
    ]
